import { Feather, Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';

const articles = [
  { title: 'Kashyap Rishi', detail: 'Origins, stories, and the wisdom carried through our gotra.', icon: 'sunny-outline' as const, color: 'gold' },
  { title: 'Bindabasini Devi', detail: 'The sacred connection between our community and the goddess.', icon: 'flower-outline' as const, color: 'green' },
  { title: 'Puja & rituals', detail: 'A growing guide to Goth Puja, Dewali, Shraddha, and more.', icon: 'book-outline' as const, color: 'blue' },
];

export default function CultureScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const [saved, setSaved] = useState<string[]>([]);
  const toggleSaved = (title: string) => setSaved((current) => current.includes(title) ? current.filter((item) => item !== title) : [...current, title]);
  return <View style={[styles.page, { backgroundColor: colors.background }]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingTop: insets.top + 14, paddingBottom: insets.bottom + 100 }}>
    <View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.mutedForeground }]}>OUR HERITAGE</Text><Text style={[styles.title, { color: colors.foreground }]}>Culture</Text></View><Pressable style={[styles.searchButton, { backgroundColor: colors.card }]}><Feather name="search" size={20} color={colors.foreground} /></Pressable></View>
    <View style={[styles.hero, { backgroundColor: colors.primary }]}><View style={[styles.heroMark, { backgroundColor: colors.accent }]}><Ionicons name="leaf-outline" size={24} color={colors.accentForeground} /></View><Text style={styles.heroTitle}>Stories worth carrying forward</Text><Text style={styles.heroCopy}>Explore the beliefs, rituals, and people that shape the Kashyap Adhikari community.</Text><Pressable style={styles.heroAction}><Text style={styles.heroActionText}>Start exploring</Text><Feather name="arrow-right" size={16} color={colors.primary} /></Pressable></View>
    <View style={styles.heading}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Explore knowledge</Text><Text style={[styles.count, { color: colors.mutedForeground }]}>6 topics</Text></View>
    <View style={styles.articleList}>{articles.map((article) => <Pressable key={article.title} style={[styles.article, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.articleIcon, { backgroundColor: article.color === 'gold' ? colors.accent : article.color === 'green' ? colors.secondary : '#DCE8EE' }]}><Ionicons name={article.icon} size={23} color={article.color === 'gold' ? colors.accentForeground : article.color === 'green' ? colors.primary : '#3C687A'} /></View><View style={styles.articleCopy}><Text style={[styles.articleTitle, { color: colors.foreground }]}>{article.title}</Text><Text style={[styles.articleDetail, { color: colors.mutedForeground }]}>{article.detail}</Text><Text style={[styles.readMore, { color: colors.primary }]}>Read article <Feather name="arrow-up-right" size={12} /></Text></View><Pressable onPress={() => toggleSaved(article.title)} hitSlop={12}><Ionicons name={saved.includes(article.title) ? 'bookmark' : 'bookmark-outline'} size={20} color={saved.includes(article.title) ? colors.accentForeground : colors.mutedForeground} /></Pressable></Pressable>)}</View>
    <View style={styles.heading}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Community archive</Text><Pressable><Text style={[styles.link, { color: colors.primary }]}>See all</Text></Pressable></View>
    <View style={styles.archiveRow}><ArchiveItem title="Family documents" value="12" icon="file-text" colors={colors} /><ArchiveItem title="Old photographs" value="28" icon="image" colors={colors} /></View>
    <View style={[styles.note, { backgroundColor: colors.secondary }]}><Feather name="info" size={17} color={colors.primary} /><Text style={[styles.noteText, { color: colors.primary }]}>This knowledge center is curated by community members and genealogy admins. Have a story to share?</Text></View>
  </ScrollView></View>;
}
function ArchiveItem({ title, value, icon, colors }: { title: string; value: string; icon: keyof typeof Feather.glyphMap; colors: ReturnType<typeof useColors> }) { return <Pressable style={[styles.archive, { backgroundColor: colors.card, borderColor: colors.border }]}><Feather name={icon} size={19} color={colors.accentForeground} /><Text style={[styles.archiveTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.archiveValue, { color: colors.mutedForeground }]}>{value}</Text></Pressable>; }
const styles = StyleSheet.create({ page: { flex: 1 }, header: { paddingHorizontal: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 22 }, eyebrow: { fontSize: 11, letterSpacing: 1.7, fontWeight: '700', marginBottom: 6 }, title: { fontSize: 30, fontWeight: '700', letterSpacing: -0.6 }, searchButton: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' }, hero: { marginHorizontal: 20, borderRadius: 21, padding: 20, marginBottom: 27 }, heroMark: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center', marginBottom: 18 }, heroTitle: { color: '#FFF9EF', fontSize: 22, lineHeight: 27, fontWeight: '700', maxWidth: 260 }, heroCopy: { color: '#D4E4D8', fontSize: 12, lineHeight: 18, marginTop: 8, maxWidth: 300 }, heroAction: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 7, backgroundColor: '#F7F3EC', borderRadius: 20, paddingHorizontal: 13, paddingVertical: 10, marginTop: 18 }, heroActionText: { color: '#1F5B45', fontSize: 12, fontWeight: '700' }, heading: { paddingHorizontal: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }, sectionTitle: { fontSize: 18, fontWeight: '700' }, count: { fontSize: 11 }, articleList: { paddingHorizontal: 20, gap: 9, marginBottom: 27 }, article: { borderWidth: 1, borderRadius: 16, padding: 13, flexDirection: 'row', alignItems: 'flex-start', gap: 11 }, articleIcon: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, articleCopy: { flex: 1 }, articleTitle: { fontSize: 14, fontWeight: '700', marginBottom: 4 }, articleDetail: { fontSize: 11, lineHeight: 16 }, readMore: { fontSize: 11, fontWeight: '700', marginTop: 8 }, link: { fontSize: 13, fontWeight: '600' }, archiveRow: { flexDirection: 'row', gap: 9, paddingHorizontal: 20, marginBottom: 20 }, archive: { flex: 1, borderWidth: 1, borderRadius: 15, padding: 13, gap: 9 }, archiveTitle: { fontSize: 12, fontWeight: '700' }, archiveValue: { fontSize: 11 }, note: { marginHorizontal: 20, borderRadius: 15, padding: 13, flexDirection: 'row', gap: 10, alignItems: 'flex-start' }, noteText: { flex: 1, fontSize: 11, lineHeight: 17 } });