import { Feather, Ionicons } from '@expo/vector-icons';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useColors } from '@/hooks/useColors';

export default function ProfileScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const [notifications, setNotifications] = useState(true);
  const [privacy, setPrivacy] = useState(false);
  const updateNotifications = (value: boolean) => { setNotifications(value); AsyncStorage.setItem('kashyap-notifications', String(value)); };
  return <View style={[styles.page, { backgroundColor: colors.background }]}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingTop: insets.top + 14, paddingBottom: insets.bottom + 100 }}>
    <View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.mutedForeground }]}>YOUR ACCOUNT</Text><Text style={[styles.title, { color: colors.foreground }]}>Profile</Text></View><Pressable><Feather name="more-horizontal" size={22} color={colors.foreground} /></Pressable></View>
    <View style={[styles.profileCard, { backgroundColor: colors.primary }]}><View style={styles.avatar}><Text style={[styles.avatarText, { color: colors.primary }]}>SU</Text></View><View style={styles.profileCopy}><Text style={styles.name}>Suman Adhikari</Text><Text style={styles.meta}>Pokhara · Member since 2026</Text><View style={styles.verified}><Ionicons name="checkmark-circle" size={13} color="#D4E4D8" /><Text style={styles.verifiedText}>Genealogy linked</Text></View></View><Pressable style={styles.edit}><Feather name="edit-2" size={16} color="#FFF9EF" /></Pressable></View>
    <Text style={[styles.sectionTitle, { color: colors.foreground }]}>Your settings</Text>
    <View style={[styles.settings, { backgroundColor: colors.card, borderColor: colors.border }]}>
      <Setting icon="bell" title="Family notifications" detail="Birthdays, events, and updates" colors={colors} right={<Switch value={notifications} onValueChange={updateNotifications} trackColor={{ false: colors.muted, true: colors.primary }} thumbColor={colors.card} />} />
      <Setting icon="globe" title="Language" detail="English · नेपाली available" colors={colors} right={<Feather name="chevron-right" size={18} color={colors.mutedForeground} />} />
      <Setting icon="shield" title="Privacy & consent" detail={privacy ? 'Family-only visibility' : 'Review your visibility'} colors={colors} onPress={() => setPrivacy((value) => !value)} right={<Feather name="chevron-right" size={18} color={colors.mutedForeground} />} />
      <Setting icon="help-circle" title="Help & feedback" detail="We are here to help" colors={colors} right={<Feather name="chevron-right" size={18} color={colors.mutedForeground} />} last />
    </View>
    <Text style={[styles.sectionTitle, { color: colors.foreground, marginTop: 27 }]}>Genealogy activity</Text>
    <View style={styles.activityRow}><Activity value="3" label="Requests" icon="git-pull-request" colors={colors} /><Activity value="1" label="Contribution" icon="edit-3" colors={colors} /><Activity value="18" label="Relatives" icon="users" colors={colors} /></View>
    <Pressable style={[styles.logout, { borderColor: colors.border }]}><Feather name="log-out" size={17} color={colors.destructive} /><Text style={[styles.logoutText, { color: colors.destructive }]}>Sign out</Text></Pressable>
    <Text style={[styles.version, { color: colors.mutedForeground }]}>Kashyap Family · Phase 1 preview</Text>
  </ScrollView></View>;
}
function Setting({ icon, title, detail, colors, right, onPress, last = false }: { icon: keyof typeof Feather.glyphMap; title: string; detail: string; colors: ReturnType<typeof useColors>; right: React.ReactNode; onPress?: () => void; last?: boolean }) { return <Pressable onPress={onPress} style={[styles.setting, !last && { borderBottomWidth: 1, borderBottomColor: colors.border }]}><View style={[styles.settingIcon, { backgroundColor: colors.secondary }]}><Feather name={icon} size={17} color={colors.primary} /></View><View style={styles.settingCopy}><Text style={[styles.settingTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.settingDetail, { color: colors.mutedForeground }]}>{detail}</Text></View>{right}</Pressable>; }
function Activity({ value, label, icon, colors }: { value: string; label: string; icon: keyof typeof Feather.glyphMap; colors: ReturnType<typeof useColors> }) { return <View style={[styles.activity, { backgroundColor: colors.card, borderColor: colors.border }]}><Feather name={icon} size={17} color={colors.accentForeground} /><Text style={[styles.activityValue, { color: colors.foreground }]}>{value}</Text><Text style={[styles.activityLabel, { color: colors.mutedForeground }]}>{label}</Text></View>; }
const styles = StyleSheet.create({ page: { flex: 1 }, header: { paddingHorizontal: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 22 }, eyebrow: { fontSize: 11, letterSpacing: 1.7, fontWeight: '700', marginBottom: 6 }, title: { fontSize: 30, fontWeight: '700', letterSpacing: -0.6 }, profileCard: { marginHorizontal: 20, borderRadius: 21, padding: 18, flexDirection: 'row', alignItems: 'center', marginBottom: 29 }, avatar: { width: 57, height: 57, borderRadius: 20, backgroundColor: '#EAD7B7', alignItems: 'center', justifyContent: 'center' }, avatarText: { fontSize: 17, fontWeight: '700' }, profileCopy: { flex: 1, marginLeft: 13 }, name: { color: '#FFF9EF', fontSize: 16, fontWeight: '700' }, meta: { color: '#D4E4D8', fontSize: 11, marginTop: 5 }, verified: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 8 }, verifiedText: { color: '#D4E4D8', fontSize: 10, fontWeight: '600' }, edit: { padding: 8 }, sectionTitle: { marginHorizontal: 20, fontSize: 18, fontWeight: '700', marginBottom: 12 }, settings: { marginHorizontal: 20, borderWidth: 1, borderRadius: 17, paddingHorizontal: 13 }, setting: { minHeight: 66, flexDirection: 'row', alignItems: 'center', gap: 11 }, settingIcon: { width: 35, height: 35, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, settingCopy: { flex: 1 }, settingTitle: { fontSize: 13, fontWeight: '700' }, settingDetail: { fontSize: 11, marginTop: 4 }, activityRow: { flexDirection: 'row', gap: 8, paddingHorizontal: 20 }, activity: { flex: 1, borderWidth: 1, borderRadius: 15, padding: 12, minHeight: 87 }, activityValue: { fontSize: 23, fontWeight: '700', marginTop: 8 }, activityLabel: { fontSize: 10, marginTop: 2 }, logout: { marginHorizontal: 20, marginTop: 27, borderWidth: 1, borderRadius: 14, paddingVertical: 13, flexDirection: 'row', gap: 8, justifyContent: 'center', alignItems: 'center' }, logoutText: { fontSize: 13, fontWeight: '700' }, version: { textAlign: 'center', fontSize: 10, marginTop: 17 } });